* bookmark-view.el - Use bookmarks to persist the current view

This package provides commands which allow storing the window configuration
(called a view) as an Emacs bookmark. This way the view is automatically
persisted and can be restored after restart.

There are alternative view packages like burly, which are more ambitious.
bookmark-view aims to be the simplest thing that marries bookmarks and window
configurations.

The main command is =bookmark-view=. If called interactively it reads a bookmark
name via =completing-read=. If a view bookmark with the given name exists, open
it, otherwise the current view is saved under that name.

Furthermore there are the commands =bookmark-view-push= and =bookmark-view-pop=
to store a stack of views. Please take a look at the source code to see all of
the available commands.

This package works well together with my [[https://github.com/minad/consult][Consult package]], which can be
configured such that =consult-buffer= directly includes the list of views.
